services:
  db:
    image: postgres:16
    container_name: elikuren-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: elikuren
      POSTGRES_USER: elikuren
      POSTGRES_PASSWORD: imgalluspark
    volumes:
      - ./data/postgres-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U elikuren -d elikuren"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ../app-elikuren-web
      dockerfile: Dockerfile.dev
    container_name: elikuren-web-dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - ../app-elikuren-web:/app
      - /app/node_modules
      - ./keys:/app/keys
    environment:
      NODE_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: ../app-elikuren-api
    container_name: elikuren-api-dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    volumes:
      - ../app-elikuren-api:/app
      - ../app-elikuren-api/keys:/app/keys
    depends_on:
      db:
        condition: service_healthy
